#!/bin/env bash
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -sha256 \
  -keyout key.pem -out cert.pem \
  -subj "/CN=localhost" \
  -addext "subjectAltName=DNS:localhost,email:levent@example.com"
